// src/lib/components/editor/Header.svelte
<script lang="ts">
	import type { HeaderData } from '@editorjs/header';

	export let data: HeaderData;
	export let level = 2;
</script>

{#if level === 1}
	<h1 class="text-3xl font-bold">{@html data.text}</h1>
{:else if level === 2}
	<h2 class="text-2xl font-bold">{@html data.text}</h2>
{:else if level === 3}
	<h3 class="text-xl font-bold">{@html data.text}</h3>
{:else if level === 4}
	<h4 class="text-lg font-bold">{@html data.text}</h4>
{:else if level === 5}
	<h5 class="text-base font-bold">{@html data.text}</h5>
{:else if level === 6}
	<h6 class="text-sm font-bold">{@html data.text}</h6>
{/if}

// components/editor/Header.vue
<template>
    <div>
      <h1 v-if="level === 1" class="text-3xl font-bold" v-html="data.text"></h1>
      <h2 v-else-if="level === 2" class="text-2xl font-bold" v-html="data.text"></h2>
      <h3 v-else-if="level === 3" class="text-xl font-bold" v-html="data.text"></h3>
      <h4 v-else-if="level === 4" class="text-lg font-bold" v-html="data.text"></h4>
      <h5 v-else-if="level === 5" class="text-base font-bold" v-html="data.text"></h5>
      <h6 v-else-if="level === 6" class="text-sm font-bold" v-html="data.text"></h6>
    </div>
  </template>
  
  <script lang="ts" setup>
  import type { HeaderData } from '@editorjs/header';
  
  defineProps({
    data: {
      type: Object as PropType<HeaderData>,
      required: true
    },
    level: {
      type: Number,
      default: 2
    }
  });
  </script>
